// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9KgAClbcj21VPqRnFZL0QHKZ0Gdqhk2E',
    appId: '1:934532670053:web:89e32b69fdc40296cb1c8c',
    messagingSenderId: '934532670053',
    projectId: 'devbaa-dwms',
    authDomain: 'devbaa-dwms.firebaseapp.com',
    storageBucket: 'devbaa-dwms.firebasestorage.app',
    measurementId: 'G-K5G25T1FX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZiJrNfzevHBmIfy9sPOyOqszzvW7nQb4',
    appId: '1:934532670053:android:406ac74d750730eecb1c8c',
    messagingSenderId: '934532670053',
    projectId: 'devbaa-dwms',
    storageBucket: 'devbaa-dwms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj53rGeDvpwjYw679fvjyQK3p_1yovyQQ',
    appId: '1:934532670053:ios:e71da57824fdaeffcb1c8c',
    messagingSenderId: '934532670053',
    projectId: 'devbaa-dwms',
    storageBucket: 'devbaa-dwms.firebasestorage.app',
    iosBundleId: 'com.devbaa.dwms',
  );
}
